import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextAuthProvider from "./Provider";
import MainConversation from "@/components/conversation/MainConversation";
import { getServerSession } from "next-auth/next";
import { nextAuthOptions } from "@/pages/api/auth/[...nextauth]";
import { GlobalContextProvider } from "@/context/GlobalContext";
import ViewFullImage from "@/components/view_image/ViewFullImage";
import Alert from "@/components/Alert";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(nextAuthOptions);
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>
        <NextAuthProvider>
          <GlobalContextProvider>
            {session && <MainConversation />}
            {children}
            <ViewFullImage />
            <Alert />
          </GlobalContextProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
